### ISSUE TITLE
Making the source a link

### ISSUE THREAD

**Issue by brettmjohnson** [larrysalibra/evernote-to-apple-notes#1]
I noticed the source URLs in the Evernote data were not formatted to be links, so I made an edit:

set evernoteData to evernoteData & "\"source\":  \"<a href='" & noteSource & "'>" & noteSource & "</a>\", "

This assumes the source is always a URL (but isn't it?).

**Comment by larrysalibra** [comment]
It looks like github may have filtered out your html? The Evernote data is meant to be JSON formatted to make it easy to programmatically add the source data to the Apple Notes if Apple Notes adds these fields in the future. There's definitely room to play around with the formatting and make it look nice.

Thanks for the suggestion!
