### ISSUE TITLE
Adding # to tags

### ISSUE THREAD

**Issue by brettmjohnson** [larrysalibra/evernote-to-apple-notes#2]
I thought it might be more useful to have a # in front of the tags in the Evernote data, so here's what I did.

if tagCounter is equal to (count of noteTags) then
                        -- don't add a common after last tag
                        set noteTagsText to noteTagsText & "#" & (name of noteTag)
                    else
                        set noteTagsText to noteTagsText & "#" & (name of noteTag & ", ")
                    end if

Obviously there's some personal preference here, but I think it does make the more specifically searchable.

**Comment by larrysalibra** [comment]
Thanks for the suggestion and for checking out the script! This of course assumes you don't have a lot of notes with hashtags in it already! 😊
