### ISSUE TITLE
Adding creation and modification dates

### ISSUE THREAD

**Issue by netfly** [larrysalibra/evernote-to-apple-notes#3]
Hi,
first of all thanks for this incredible script .... it helped me a lot.

Ich just added a few things.

set newNote to make new note at folder noteNotebookName with properties {name:noteName, body:noteBody, creation date:noteCreated, modification date:noteModified}

Maybe you can add this to your code.
This will create the new notes with the correct dates, like the originals.

hope it helps too :)

**Comment by larrysalibra** [comment]
Thanks @netfly! Great find...I'll add this.

**Comment by netfly** [comment]
Welcome and thanks :)
